name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:     
    -
        name: Git pull
        run: git pull 
    -
        name: Login to Docker Hub 
        uses: docker/login-action@v1
        with:
          username: oldviking
          password: ${{ secrets.DOCKERHUB_PW }}
          
    -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: oldviking/bazaro:latest
